// The connector protocol (architecture §7.1): how a Turgon worker drives a
// connector that runs outside it, such as a Camel/Java connector in a
// sidecar container. The worker keeps everything that governs a write
// (policy, approval, idempotency records, the rate governor, the circuit
// breaker, audit); the connector only talks to its system.
//
// Errors are gRPC status codes:
//   INVALID_ARGUMENT    the payload or ID is not valid for the system
//   FAILED_PRECONDITION the system refused the write (a business rule)
//   NOT_FOUND           Read: no such record
//   UNIMPLEMENTED       the connector does not do this (Simulate: no dry run)
//   UNAUTHENTICATED     the worker did not send the sidecar's token
//   ABORTED             the instance is not configured (the sidecar
//                       restarted): the worker configures it again and
//                       repeats the call once
//   anything else       transient: the worker retries
// Messages are shown to operators: they name fields, never values.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: turgon/connector/v1/connector.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The protocol version this file describes.
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_V1          Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_V1",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_V1":          1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_turgon_connector_v1_connector_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_turgon_connector_v1_connector_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=turgon.connector.v1.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type DescribeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=turgon.connector.v1.Protocol" json:"protocol,omitempty"`
	// The connector's manifest name and version, such as sap-ecc 0.4.0.
	Connector string `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// What it implements beyond Commit: "simulate", "confirm", "read",
	// "poll", "export", "check", "stream".
	Capabilities  []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *DescribeResponse) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chosen by the worker, unique per configuration (endpoint and generation).
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The connector's compiled configuration: the runtime spec's connector
	// entry (pkg/compiler.ConnectorConfig) as JSON, without secret values.
	Spec []byte `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// The value of the entry's secretRef, and of every secretRef inside its
	// configuration, by reference.
	Secret        string            `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Secrets       map[string]string `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ConfigureRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConfigureRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ConfigureRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ConfigureRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ConfigureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The events of this instance that arrive by Stream rather than Poll.
	StreamedEvents []string `protobuf:"bytes,1,rep,name=streamed_events,json=streamedEvents,proto3" json:"streamed_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetStreamedEvents() []string {
	if x != nil {
		return x.StreamedEvents
	}
	return nil
}

type InstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRequest) Reset() {
	*x = InstanceRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRequest) ProtoMessage() {}

func (x *InstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRequest.ProtoReflect.Descriptor instead.
func (*InstanceRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{4}
}

func (x *InstanceRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{5}
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Fix           string                 `protobuf:"bytes,4,opt,name=fix,proto3" json:"fix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{6}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CheckResult) GetFix() string {
	if x != nil {
		return x.Fix
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CheckResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{7}
}

func (x *CheckResponse) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Instance       string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Operation      string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// JSON.
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{8}
}

func (x *WriteRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *WriteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *WriteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WriteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{9}
}

func (x *WriteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ConfirmRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Instance  string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Operation string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// Commit's result.
	Result        []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ConfirmRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ConfirmRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{11}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{12}
}

func (x *ReadRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ReadRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON.
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{13}
}

func (x *ReadResponse) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	After         int64                  `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{14}
}

func (x *PollRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PollRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *PollRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PollRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within the source and stable across re-reads.
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position int64  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// JSON.
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{16}
}

func (x *PollResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{17}
}

func (x *ExportRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ExportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExportRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRecord) Reset() {
	*x = ExportRecord{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRecord) ProtoMessage() {}

func (x *ExportRecord) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRecord.ProtoReflect.Descriptor instead.
func (*ExportRecord) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{18}
}

func (x *ExportRecord) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StreamRequest_Open
	//	*StreamRequest_Ack
	Request       isStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{19}
}

func (x *StreamRequest) GetRequest() isStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamRequest) GetOpen() *StreamOpen {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *StreamRequest) GetAck() *StreamAck {
	if x != nil {
		if x, ok := x.Request.(*StreamRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isStreamRequest_Request interface {
	isStreamRequest_Request()
}

type StreamRequest_Open struct {
	// The first message: what to subscribe to.
	Open *StreamOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type StreamRequest_Ack struct {
	// Every later one: a batch the worker has stored.
	Ack *StreamAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*StreamRequest_Open) isStreamRequest_Request() {}

func (*StreamRequest_Ack) isStreamRequest_Request() {}

type StreamOpen struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Event    string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Where to resume, as a previous batch gave it (empty: from now).
	Resume        []byte `protobuf:"bytes,3,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOpen) Reset() {
	*x = StreamOpen{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpen) ProtoMessage() {}

func (x *StreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpen.ProtoReflect.Descriptor instead.
func (*StreamOpen) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{20}
}

func (x *StreamOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *StreamOpen) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamOpen) GetResume() []byte {
	if x != nil {
		return x.Resume
	}
	return nil
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         uint64                 `protobuf:"varint,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{21}
}

func (x *StreamAck) GetBatch() uint64 {
	if x != nil {
		return x.Batch
	}
	return 0
}

type StreamBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numbers the batch within the stream, for its acknowledgement.
	Batch  uint64   `protobuf:"varint,1,opt,name=batch,proto3" json:"batch,omitempty"`
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Where to resume after this batch, if the system has positions.
	Resume        []byte `protobuf:"bytes,3,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBatch) Reset() {
	*x = StreamBatch{}
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBatch) ProtoMessage() {}

func (x *StreamBatch) ProtoReflect() protoreflect.Message {
	mi := &file_turgon_connector_v1_connector_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBatch.ProtoReflect.Descriptor instead.
func (*StreamBatch) Descriptor() ([]byte, []int) {
	return file_turgon_connector_v1_connector_proto_rawDescGZIP(), []int{22}
}

func (x *StreamBatch) GetBatch() uint64 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *StreamBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StreamBatch) GetResume() []byte {
	if x != nil {
		return x.Resume
	}
	return nil
}

var File_turgon_connector_v1_connector_proto protoreflect.FileDescriptor

const file_turgon_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	"#turgon/connector/v1/connector.proto\x12\x13turgon.connector.v1\"L\n" +
	"\x0fDescribeRequest\x129\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1d.turgon.connector.v1.ProtocolR\bprotocol\"\xa9\x01\n" +
	"\x10DescribeResponse\x129\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1d.turgon.connector.v1.ProtocolR\bprotocol\x12\x1c\n" +
	"\tconnector\x18\x02 \x01(\tR\tconnector\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\x80\x02\n" +
	"\x10ConfigureRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12L\n" +
	"\asecrets\x18\x05 \x03(\v22.turgon.connector.v1.ConfigureRequest.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x11ConfigureResponse\x12'\n" +
	"\x0fstreamed_events\x18\x01 \x03(\tR\x0estreamedEvents\"-\n" +
	"\x0fInstanceRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"\x11\n" +
	"\x0fReleaseResponse\"[\n" +
	"\vCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x10\n" +
	"\x03fix\x18\x04 \x01(\tR\x03fix\"K\n" +
	"\rCheckResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .turgon.connector.v1.CheckResultR\aresults\"\x8b\x01\n" +
	"\fWriteRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"'\n" +
	"\rWriteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"b\n" +
	"\x0eConfirmRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"\x11\n" +
	"\x0fConfirmResponse\"W\n" +
	"\vReadRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"&\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\"k\n" +
	"\vPollRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"a\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"B\n" +
	"\fPollResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.turgon.connector.v1.EventR\x06events\"?\n" +
	"\rExportRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x90\x01\n" +
	"\fExportRecord\x12E\n" +
	"\x06fields\x18\x01 \x03(\v2-.turgon.connector.v1.ExportRecord.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\rStreamRequest\x125\n" +
	"\x04open\x18\x01 \x01(\v2\x1f.turgon.connector.v1.StreamOpenH\x00R\x04open\x122\n" +
	"\x03ack\x18\x02 \x01(\v2\x1e.turgon.connector.v1.StreamAckH\x00R\x03ackB\t\n" +
	"\arequest\"V\n" +
	"\n" +
	"StreamOpen\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x16\n" +
	"\x06resume\x18\x03 \x01(\fR\x06resume\"!\n" +
	"\tStreamAck\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\x04R\x05batch\"o\n" +
	"\vStreamBatch\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\x04R\x05batch\x122\n" +
	"\x06events\x18\x02 \x03(\v2\x1a.turgon.connector.v1.EventR\x06events\x12\x16\n" +
	"\x06resume\x18\x03 \x01(\fR\x06resume*5\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPROTOCOL_V1\x10\x012\xa5\a\n" +
	"\tConnector\x12W\n" +
	"\bDescribe\x12$.turgon.connector.v1.DescribeRequest\x1a%.turgon.connector.v1.DescribeResponse\x12Z\n" +
	"\tConfigure\x12%.turgon.connector.v1.ConfigureRequest\x1a&.turgon.connector.v1.ConfigureResponse\x12U\n" +
	"\aRelease\x12$.turgon.connector.v1.InstanceRequest\x1a$.turgon.connector.v1.ReleaseResponse\x12Q\n" +
	"\x05Check\x12$.turgon.connector.v1.InstanceRequest\x1a\".turgon.connector.v1.CheckResponse\x12Q\n" +
	"\bSimulate\x12!.turgon.connector.v1.WriteRequest\x1a\".turgon.connector.v1.WriteResponse\x12O\n" +
	"\x06Commit\x12!.turgon.connector.v1.WriteRequest\x1a\".turgon.connector.v1.WriteResponse\x12T\n" +
	"\aConfirm\x12#.turgon.connector.v1.ConfirmRequest\x1a$.turgon.connector.v1.ConfirmResponse\x12K\n" +
	"\x04Read\x12 .turgon.connector.v1.ReadRequest\x1a!.turgon.connector.v1.ReadResponse\x12K\n" +
	"\x04Poll\x12 .turgon.connector.v1.PollRequest\x1a!.turgon.connector.v1.PollResponse\x12Q\n" +
	"\x06Export\x12\".turgon.connector.v1.ExportRequest\x1a!.turgon.connector.v1.ExportRecord0\x01\x12R\n" +
	"\x06Stream\x12\".turgon.connector.v1.StreamRequest\x1a .turgon.connector.v1.StreamBatch(\x010\x01B`\n" +
	"\x17dev.turgon.connector.v1P\x01ZCgithub.com/fduser123-coding/turgon/pkg/connector/remote/connectorpbb\x06proto3"

var (
	file_turgon_connector_v1_connector_proto_rawDescOnce sync.Once
	file_turgon_connector_v1_connector_proto_rawDescData []byte
)

func file_turgon_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_turgon_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_turgon_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turgon_connector_v1_connector_proto_rawDesc), len(file_turgon_connector_v1_connector_proto_rawDesc)))
	})
	return file_turgon_connector_v1_connector_proto_rawDescData
}

var file_turgon_connector_v1_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turgon_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_turgon_connector_v1_connector_proto_goTypes = []any{
	(Protocol)(0),             // 0: turgon.connector.v1.Protocol
	(*DescribeRequest)(nil),   // 1: turgon.connector.v1.DescribeRequest
	(*DescribeResponse)(nil),  // 2: turgon.connector.v1.DescribeResponse
	(*ConfigureRequest)(nil),  // 3: turgon.connector.v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 4: turgon.connector.v1.ConfigureResponse
	(*InstanceRequest)(nil),   // 5: turgon.connector.v1.InstanceRequest
	(*ReleaseResponse)(nil),   // 6: turgon.connector.v1.ReleaseResponse
	(*CheckResult)(nil),       // 7: turgon.connector.v1.CheckResult
	(*CheckResponse)(nil),     // 8: turgon.connector.v1.CheckResponse
	(*WriteRequest)(nil),      // 9: turgon.connector.v1.WriteRequest
	(*WriteResponse)(nil),     // 10: turgon.connector.v1.WriteResponse
	(*ConfirmRequest)(nil),    // 11: turgon.connector.v1.ConfirmRequest
	(*ConfirmResponse)(nil),   // 12: turgon.connector.v1.ConfirmResponse
	(*ReadRequest)(nil),       // 13: turgon.connector.v1.ReadRequest
	(*ReadResponse)(nil),      // 14: turgon.connector.v1.ReadResponse
	(*PollRequest)(nil),       // 15: turgon.connector.v1.PollRequest
	(*Event)(nil),             // 16: turgon.connector.v1.Event
	(*PollResponse)(nil),      // 17: turgon.connector.v1.PollResponse
	(*ExportRequest)(nil),     // 18: turgon.connector.v1.ExportRequest
	(*ExportRecord)(nil),      // 19: turgon.connector.v1.ExportRecord
	(*StreamRequest)(nil),     // 20: turgon.connector.v1.StreamRequest
	(*StreamOpen)(nil),        // 21: turgon.connector.v1.StreamOpen
	(*StreamAck)(nil),         // 22: turgon.connector.v1.StreamAck
	(*StreamBatch)(nil),       // 23: turgon.connector.v1.StreamBatch
	nil,                       // 24: turgon.connector.v1.ConfigureRequest.SecretsEntry
	nil,                       // 25: turgon.connector.v1.ExportRecord.FieldsEntry
}
var file_turgon_connector_v1_connector_proto_depIdxs = []int32{
	0,  // 0: turgon.connector.v1.DescribeRequest.protocol:type_name -> turgon.connector.v1.Protocol
	0,  // 1: turgon.connector.v1.DescribeResponse.protocol:type_name -> turgon.connector.v1.Protocol
	24, // 2: turgon.connector.v1.ConfigureRequest.secrets:type_name -> turgon.connector.v1.ConfigureRequest.SecretsEntry
	7,  // 3: turgon.connector.v1.CheckResponse.results:type_name -> turgon.connector.v1.CheckResult
	16, // 4: turgon.connector.v1.PollResponse.events:type_name -> turgon.connector.v1.Event
	25, // 5: turgon.connector.v1.ExportRecord.fields:type_name -> turgon.connector.v1.ExportRecord.FieldsEntry
	21, // 6: turgon.connector.v1.StreamRequest.open:type_name -> turgon.connector.v1.StreamOpen
	22, // 7: turgon.connector.v1.StreamRequest.ack:type_name -> turgon.connector.v1.StreamAck
	16, // 8: turgon.connector.v1.StreamBatch.events:type_name -> turgon.connector.v1.Event
	1,  // 9: turgon.connector.v1.Connector.Describe:input_type -> turgon.connector.v1.DescribeRequest
	3,  // 10: turgon.connector.v1.Connector.Configure:input_type -> turgon.connector.v1.ConfigureRequest
	5,  // 11: turgon.connector.v1.Connector.Release:input_type -> turgon.connector.v1.InstanceRequest
	5,  // 12: turgon.connector.v1.Connector.Check:input_type -> turgon.connector.v1.InstanceRequest
	9,  // 13: turgon.connector.v1.Connector.Simulate:input_type -> turgon.connector.v1.WriteRequest
	9,  // 14: turgon.connector.v1.Connector.Commit:input_type -> turgon.connector.v1.WriteRequest
	11, // 15: turgon.connector.v1.Connector.Confirm:input_type -> turgon.connector.v1.ConfirmRequest
	13, // 16: turgon.connector.v1.Connector.Read:input_type -> turgon.connector.v1.ReadRequest
	15, // 17: turgon.connector.v1.Connector.Poll:input_type -> turgon.connector.v1.PollRequest
	18, // 18: turgon.connector.v1.Connector.Export:input_type -> turgon.connector.v1.ExportRequest
	20, // 19: turgon.connector.v1.Connector.Stream:input_type -> turgon.connector.v1.StreamRequest
	2,  // 20: turgon.connector.v1.Connector.Describe:output_type -> turgon.connector.v1.DescribeResponse
	4,  // 21: turgon.connector.v1.Connector.Configure:output_type -> turgon.connector.v1.ConfigureResponse
	6,  // 22: turgon.connector.v1.Connector.Release:output_type -> turgon.connector.v1.ReleaseResponse
	8,  // 23: turgon.connector.v1.Connector.Check:output_type -> turgon.connector.v1.CheckResponse
	10, // 24: turgon.connector.v1.Connector.Simulate:output_type -> turgon.connector.v1.WriteResponse
	10, // 25: turgon.connector.v1.Connector.Commit:output_type -> turgon.connector.v1.WriteResponse
	12, // 26: turgon.connector.v1.Connector.Confirm:output_type -> turgon.connector.v1.ConfirmResponse
	14, // 27: turgon.connector.v1.Connector.Read:output_type -> turgon.connector.v1.ReadResponse
	17, // 28: turgon.connector.v1.Connector.Poll:output_type -> turgon.connector.v1.PollResponse
	19, // 29: turgon.connector.v1.Connector.Export:output_type -> turgon.connector.v1.ExportRecord
	23, // 30: turgon.connector.v1.Connector.Stream:output_type -> turgon.connector.v1.StreamBatch
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_turgon_connector_v1_connector_proto_init() }
func file_turgon_connector_v1_connector_proto_init() {
	if File_turgon_connector_v1_connector_proto != nil {
		return
	}
	file_turgon_connector_v1_connector_proto_msgTypes[19].OneofWrappers = []any{
		(*StreamRequest_Open)(nil),
		(*StreamRequest_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turgon_connector_v1_connector_proto_rawDesc), len(file_turgon_connector_v1_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_turgon_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_turgon_connector_v1_connector_proto_depIdxs,
		EnumInfos:         file_turgon_connector_v1_connector_proto_enumTypes,
		MessageInfos:      file_turgon_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_turgon_connector_v1_connector_proto = out.File
	file_turgon_connector_v1_connector_proto_goTypes = nil
	file_turgon_connector_v1_connector_proto_depIdxs = nil
}
