#!/bin/sh
# Regenerates the Go code for the connector protocol (proto/). Needs protoc
# and the protoc-gen-go / protoc-gen-go-grpc plugins on PATH; CI checks the
# committed code is up to date. The Java code is generated by Gradle.
set -eu
cd "$(dirname "$0")/.."
out=pkg/connector/remote/connectorpb
mkdir -p "$out"
protoc -I proto \
  --go_out=. --go_opt=module=github.com/fduser123-coding/turgon \
  --go-grpc_out=. --go-grpc_opt=module=github.com/fduser123-coding/turgon \
  proto/turgon/connector/v1/connector.proto
